### ISSUE TITLE
help

### ISSUE THREAD

**Issue by Xylomania** [calclover2514/BEE2.4-Installer-Automatic#2]
It just says no internet connection

Do i need to set something up?

**Comment by programmer2514** [comment]
I have been unable to reproduce this issue on any PC with an internet connection. Did you run the installer as administrator? It could be that the application's files somehow got corrupted. Please try the following and tell me if it works (Sorry for the late response, school's been crazy lately):

1. Navigate to `%temp%` in File Explorer
2. Delete the `BEEMOD2` folder (if it exists)
3. Delete the following files (if they exist): `internet_check.tmp`, `beemod.json`, `packages.json`
4. Navigate to `%appdata%\BEEMOD2\` in File Explorer
5. Delete the following files (if they exist): `last_update.txt`, `pck_version.txt`, `version.txt`
6. Navigate to `C:\Program Files\` in File Explorer
7. Delete the `BEEMOD2` folder (if it exists)
8. Try running the installer again.

**Comment by Xylomania** [comment]
Alright I'll try later and tell you if it works!

**Comment by Xylomania** [comment]
Right. The installer works however bee2 in general does not, I know it's
not the installers fault but I'm just wondering if theres a way to fix the
huge error screens?

**Comment by programmer2514** [comment]
What error are you getting when starting BEE2?
Because certain errors could actually have been caused by the installer :/
