### ISSUE TITLE
windows defender detects this as a trojan

### ISSUE THREAD

**Issue by LostGameDev** [calclover2514/BEE2.4-Installer-Automatic#3]

**Comment by programmer2514** [comment]
Unfortunately, there's nothing I can do about this. It downloads, integrates with, and runs a third-party piece of software - behavior typical of a trojan - hence why Defender may falsely mark it as such. However, I can assure you that it is not a trojan or any other type of virus, and you can feel free to browse the source code and see for yourself :)
